* basho_bench
** Overview

   [[https://github.com/basho/basho_bench/blob/master/README.org][For general information about basho_bench, please refer to the original README]]

   Basho Bench is a benchmarking tool created to conduct accurate and
   repeatable performance tests and stress tests, and produce
   performance graphs.
    
** Modification

   Two files are added for benchmarking floppystore: 
   - src/basho_bench_driver_floppystore.erl: defines the initialization of a benchmarking thread and how it executes put/get operations.
   - examples/floppstore.config: contains benchmark parameters.

** Run a benchmark 
#+BEGIN_SRC shell
$ ./basho_bench examples/floppystore.config
#+END_SRC

   At the end of the benchmark, results will be available in CSV
   format in the =tests/current/= directory. Now you can generate a
   graph:

#+BEGIN_SRC shell
$ make results
$ open tests/current/summary.png
#+END_SRC

** Limitations
   Right now it only has put/get interfaces and there is no support for transaction.
   It only put/get for riak_dt_gcounter.
